#!/bin/sh

"$TESTDIR/hghave" gpg openssl || exit 80

hg init
echo "Hello" > a.txt
hg add a.txt
echo "% Commit with no signature"
hg commit -m "Unsigned" -d '1000 0'

cat >> $HGRCPATH <<EOF
[extensions]
commitsigs = $TESTDIR/../commitsigs.py

[commitsigs]
gnupg.flags = --no-permission-warning --no-secmem-warning \
              --homedir $TESTDIR/gpg

EOF

echo "World" >> a.txt
echo "% Commit with GnuPG signature"
hg commit -m "GnuPG" -d '2000 0'

cat >> $HGRCPATH <<EOF
[commitsigs]
scheme = openssl
openssl.pubkey = $TESTDIR/openssl/pub.pem
openssl.seckey = $TESTDIR/openssl/sec.pem
EOF

echo "!" >> a.txt
echo "% Commit with OpenSSL signature"
hg commit -m "OpenSSL" -d '3000 0'

hg verifysigs | sed 's|:[0-9a-f]\+:|:XXXXXXXXXXXX:|'

cat >> $HGRCPATH <<EOF
[commitsigs]
scheme = x
EOF

echo "% unknown scheme"
hg status

true
