#!/bin/sh

"$TESTDIR/hghave" gpg openssl || exit 80

cat >> $HGRCPATH <<EOF
[extensions]
commitsigs = $TESTDIR/../commitsigs.py

[commitsigs]
gnupg.flags = --no-permission-warning --no-secmem-warning \
              --homedir $TESTDIR/gpg

EOF

echo '% Testing with GnuPG'
hg init gnupg
cd gnupg
echo "Hello" > a.txt
hg add
hg commit -m First -d '1000 0'

echo "World" >> a.txt
hg commit -m Second -d '2000 0'

hg verifysigs | sed 's|:[0-9a-f]\+:|:XXXXXXXXXXXX:|'


cd ..

echo '% Testing with OpenSSL'
hg init openssl
cd openssl

cat >> $HGRCPATH <<EOF
[commitsigs]
scheme = openssl
openssl.pubkey = $TESTDIR/openssl/pub.pem
openssl.seckey = $TESTDIR/openssl/sec.pem
EOF

echo "Hello" > a.txt
hg add
hg commit -m First -d '1000 0'

echo "World" >> a.txt
hg commit -m Second -d '2000 0'

hg verifysigs | sed 's|:[0-9a-f]\+:|:XXXXXXXXXXXX:|'


cat >> $HGRCPATH <<EOF
[commitsigs]
scheme = x
EOF

echo "% unknown scheme"
hg status

true
